### PR TITLE
Refactor font styles for Rails

### PR DESCRIPTION
**Pull request by yhirano55**
Currently, I feel source codes are not easy to read for us. So I've refactored CSS. Mainly, I changed Typography.

### CODE REVIEW

**Comment by yhirano55** [comment]
I reproduced error same as travis:

```
% docker run --rm -v $PWD:/sdoc -it ruby:latest bash
root@ab455a63d70a:/# cd sdoc
root@ab455a63d70a:/sdoc# gem update --system
Latest version already installed. Done.
root@ab455a63d70a:/sdoc# gem install bundler
Fetching: bundler-1.16.1.gem (100%)
Successfully installed bundler-1.16.1
1 gem installed
root@ab455a63d70a:/sdoc# rdoc=master bundle install
The git source `git://github.com/ruby/rdoc.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
Fetching git://github.com/ruby/rdoc.git
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Fetching rake 10.5.0
Installing rake 10.5.0
Using bundler 1.16.1
Fetching hoe 3.17.0
Installing hoe 3.17.0
Fetching minitest 5.11.3
Installing minitest 5.11.3
Using rdoc 6.0.3 from git://github.com/ruby/rdoc.git (at master@991bc7b)
Using sdoc 1.0.0 from source at `.`
Bundle complete! 5 Gemfile dependencies, 6 gems now installed.
Bundled gems are installed into `/usr/local/bundle`
root@ab455a63d70a:/sdoc# rdoc=master bundle exec rake
Run options: --seed 23508

# Running:

.../usr/bin/env: 'ruby -KU': No such file or directory
/usr/bin/env: 'ruby -KU': No such file or directory
F...

Finished in 0.014915s, 469.3356 runs/s, 1340.9589 assertions/s.

  1) Failure:
RDoc::Generator::SDoc#test_0005_should display SDoc version on -v or --version [/sdoc/spec/rdoc_generator_spec.rb:45]:
--- expected
+++ actual
@@ -1,2 +1 @@
-# encoding: UTF-8
-"1.0.0"
+""


7 runs, 20 assertions, 1 failures, 0 errors, 0 skips
rake aborted!
Command failed with status (1): [ruby -I"lib:spec" -I"/usr/local/bundle/gems/rake-10.5.0/lib" "/usr/local/bundle/gems/rake-10.5.0/lib/rake/rake_test_loader.rb" "spec/*_spec.rb" ]
/usr/local/bundle/bin/bundle:104:in `load'
/usr/local/bundle/bin/bundle:104:in `<main>'
Tasks: TOP => default => test
(See full trace by running task with --trace)
```

**Comment by yhirano55** [comment]
@robin850 Please code review this PR. How do you feel about this?

**Comment by robin850** [comment]
@yhirano55 : Hey, sorry I'm not yet sure what we will do with this. We may have a brand new theme for the next release but nothing is sure yet, we need to see. I'll come back to you pretty soon !

**Comment by zzak** [comment]
Thanks for your PR, I think we'll close this though since there is plans for a refresh.

**Pull request closed without merging**
