### PR TITLE
Monkey patch `ToHtmlCrossref` to modify ref links

### PR DESCRIPTION
**Pull request by jonathanhefner**
Prior to this commit, postprocessing was used to unlink unintentional ref links and style unstyled code ref links.  Postprocessing only affects the final generator output, which is generally more robust.  But in these cases, it would be more consistent for intermediate consumers of `RDoc::CodeObject#description` to also see these changes.

This commit instead monkey patches `RDoc::Markup::ToHtmlCrossref` so that it returns bare text for unintentional ref links and wraps unstyled code ref links with `<code></code>`.  Monkey patching RDoc is not ideal, but it allows all consumers of `RDoc::CodeObject#description` to see these changes.

### CODE REVIEW

**Comment by zzak** [comment]
@jonathanhefner This [breaks builds](https://buildkite.com/rails/docs-preview/builds/7919#01946859-4dad-43c9-808f-2ee5f2e1f19a/142-598) with newer RDoc (6.10.0+), could you take a look please? :bow:

We might be able to upstream this patch if we can make it configurable.

**Comment by p8** [comment]
It seems https://github.com/ruby/rdoc/pull/1259 breaks this but added the same functionality upstream.

**Comment by jonathanhefner** [comment]
@zzak @p8 Fixed in #374.

By the way, it looks like unit tests are no longer running via GitHub Actions on PRs...?  The last PR they ran for was #365 (not related, just happens to be the last one they ran for).

**Comment by zzak** [comment]
@jonathanhefner Thanks for the quick fix and your investigation.

> unit tests are no longer running via GitHub Actions on PR

I don't have access to the repo since it moved to the Rails org, so I'm not sure. I just checked and it looks like the transfer happened around March 2023, so they were definitely running after that. :thinking:

**Comment by jonathanhefner** [comment]
Hmm, I checked the GitHub Actions tab, and saw this:

sdoc-tests-disabled

So I clicked "Enable workflow".

I can understand automatically disabling the nightly runs, but disabling the action on PRs seems presumptuous...

**Comment by zzak** [comment]
Good catch, I didn't even realize (or forgot) there was a nightly but we probably don't need it?

**Pull request merged**
