### PR TITLE
Rework typography

### PR DESCRIPTION
**Pull request by jonathanhefner**
This PR is divided into several commits.  Together, these commits rework the typography of rendered documentation, including font faces and sizes, margins and spacing, link appearance, and color scheme.

See the individual commits for specific changes, or see the screenshots below for the overall result.  All screenshots — both before and after — were taken in Firefox on Ubuntu with DejaVu Serif (desktop @ 18px, mobile @ 16px) as the default font and DejaVu Sans Mono (desktop @ 17px, mobile @ 16px) as the default monospace font.

| Before | After | Before (mobile) | After (mobile) |
| --- | --- | --- | --- |
| before1 | after1 | mbefore1 | mafter1 |
| before2 | after2 | mbefore2 | mafter2 |
| before3 | after3 | mbefore3 | mafter3 |
| before4 | after4 | mbefore4 | mafter4 |
| before5 | after5 | mbefore5 | mafter5 |
| before6 | after6 | mbefore6 | mafter6 |
| before7 | after7 | mbefore7 | mafter7 |
| before8 | after8 | mbefore8 | mafter8 |
| before9 | after9 | mbefore9 | mafter9 |

### CODE REVIEW

**Comment by p8** [comment]
Thanks for working on this @jonathanhefner !

On OSX using Firefox 116.0.2 the vertical centering of the sidebar items seems a little off.
It's also pretty hard to read for me (compared to the existing version):
image

I'm not sure what the design direction of SDoc is.
Should it be inline with the guides, the Rails homepage, or completely separate and optimized for readability?
So I can't comment on the proposed changes in that context.

**Comment by jonathanhefner** [comment]
> On OSX using Firefox 116.0.2 the vertical centering of the sidebar items seems a little off. It's also pretty hard to read for me (compared to the existing version):

The styling for the tree is unfortunately very brittle.  As you noticed when working on dark mode, it uses a repeating background image and exact element heights for striping.  Eventually I want to address that too, but for now I can force the tree to use the previous font.  (That is what I am doing for the search results; it just didn't appear to be necessary for the tree.)

> I'm not sure what the design direction of SDoc is. Should it be inline with the guides, the Rails homepage, or completely separate and optimized for readability?

The goal of this rework is to let developers read documentation using their preferred fonts and font sizes.  Contrast that to the Rails homepage, where the goal is to market Rails.  There is some overlap of course (for example, brand color), but there are many design decisions that are fine for marketing material but not for documentation.

With regards to the guides, in my opinion, they should also respect user font preferences.  But that's outside the scope of this PR. :wink:

**Comment by jonathanhefner** [comment]
I just noticed this also fixes a styling issue with unordered lists nested in ordered lists.  The [former `ol li` rule always took precedence over the `ul li` rule](https://github.com/rails/sdoc/blob/edb3ec894d2a5d0fd4a45dbbb6a3d359654a30e6/lib/rdoc/generator/template/rails/resources/css/main.css#L132-L140), so an unordered list nested inside an ordered list would always be styled as an ordered list too.

__Before__

nested-list-before

__After__

nested-list-after

**Comment by jonathanhefner** [comment]
I've updated this PR to force the tree to use its original font.

I think this PR offers a large improvement, so I am going to merge.  If we decide we want to force all of the documentation to use a particular font or font size, it will be an easy change.  All of the styles in this PR scale based on the root font size and the value of `var(--line-height)`.

**Pull request merged**
